--
-- File generated with SQLiteStudio v3.4.8 on T4 Thg6 4 16:13:00 2025
--
-- Text encoding used: System
--
PRAGMA foreign_keys = ON;

-- Table: InputInv
CREATE TABLE IF NOT EXISTS InputInv (
    nbmst                    TEXT,
    khmshdon                 TEXT,
    khhdon                   TEXT,
    shdon                    TEXT,
    cqt                      TEXT,
    cttkhac                  TEXT,
    dvtte                    TEXT,
    hdon                     TEXT,
    hsgcma                   TEXT,
    hsgoc                    TEXT,
    hthdon                   TEXT,
    htttoan                  TEXT,
    id                       TEXT PRIMARY KEY
                                  NOT NULL,
    idtbao                   TEXT,
    khdon                    TEXT,
    khhdgoc                  TEXT,
    khmshdgoc                TEXT,
    lhdgoc                   TEXT,
    mhdon                    TEXT,
    mtdiep                   TEXT,
    mtdtchieu                TEXT,
    nbdchi                   TEXT,
    chma                     TEXT,
    chten                    TEXT,
    nbhdktngay               TEXT,
    nbhdktso                 TEXT,
    nbhdso                   TEXT,
    nblddnbo                 TEXT,
    nbptvchuyen              TEXT,
    nbstkhoan                TEXT,
    nbten                    TEXT,
    nbtnhang                 TEXT,
    nbtnvchuyen              TEXT,
    nbttkhac                 TEXT,
    ncma                     TEXT,
    ncnhat                   TEXT,
    ngcnhat                  TEXT,
    nky                      TEXT,
    nmdchi                   TEXT,
    nmmst                    TEXT,
    nmstkhoan                TEXT,
    nmten                    TEXT,
    nmtnhang                 TEXT,
    nmtnmua                  TEXT,
    nmttkhac                 TEXT,
    ntao                     TEXT,
    ntnhan                   TEXT,
    pban                     TEXT,
    ptgui                    TEXT,
    shdgoc                   TEXT,
    tchat                    TEXT,
    tdlap                    TEXT,
    tgia                     REAL,
    tgtcthue                 REAL,
    tgtthue                  REAL,
    tgtttbchu                TEXT,
    tgtttbso                 REAL,
    thdon                    TEXT,
    thlap                    TEXT,
    thttlphi                 TEXT,
    thttltsuat               TEXT,
    tlhdon                   TEXT,
    ttcktmai                 REAL,
    tthai                    TEXT,
    ttkhac                   TEXT,
    tttbao                   TEXT,
    ttttkhac                 TEXT,
    ttxly                    TEXT,
    tvandnkntt               TEXT,
    mhso                     TEXT,
    ladhddt                  TEXT,
    mkhang                   TEXT,
    nbsdthoai                TEXT,
    nbdctdtu                 TEXT,
    nbfax                    TEXT,
    nbwebsite                TEXT,
    nbcks                    TEXT,
    nmsdthoai                TEXT,
    nmdctdtu                 TEXT,
    nmcmnd                   TEXT,
    nmcks                    TEXT,
    bhphap                   TEXT,
    hddunlap                 TEXT,
    gchdgoc                  TEXT,
    tbhgtngay                TEXT,
    bhpldo                   TEXT,
    bhpcbo                   TEXT,
    bhpngay                  TEXT,
    tdlhdgoc                 TEXT,
    tgtphi                   TEXT,
    unhiem                   TEXT,
    mstdvnunlhdon            TEXT,
    tdvnunlhdon              TEXT,
    nbmdvqhnsach             TEXT,
    nbsqdinh                 TEXT,
    nbncqdinh                TEXT,
    nbcqcqdinh               TEXT,
    nbhtban                  TEXT,
    nmmdvqhnsach             TEXT,
    nmddvchden               TEXT,
    nmtgvchdtu               TEXT,
    nmtgvchdden              TEXT,
    nbtnban                  TEXT,
    dcdvnunlhdon             TEXT,
    dksbke                   TEXT,
    dknlbke                  TEXT,
    thtttoan                 TEXT,
    msttcgp                  TEXT,
    cqtcks                   TEXT,
    gchu                     TEXT,
    kqcht                    TEXT,
    hdntgia                  TEXT,
    tgtkcthue                TEXT,
    tgtkhac                  TEXT,
    nmshchieu                TEXT,
    nmnchchieu               TEXT,
    nmnhhhchieu              TEXT,
    nmqtich                  TEXT,
    ktkhthue                 TEXT,
    qrcode                   TEXT,
    ttmstten                 TEXT,
    ladhddtten               TEXT,
    hdxkhau                  TEXT,
    hdxkptquan               TEXT,
    hdgktkhthue              TEXT,
    hdonLquans               TEXT,
    tthdclquan               TEXT,
    pdndungs                 TEXT,
    hdtbssrses               TEXT,
    hdTrung                  TEXT,
    isHDTrung                TEXT,
    LastDownloadedDetailDate TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
);


-- Table: InputInvDetails
CREATE TABLE IF NOT EXISTS InputInvDetails (
    idhdon     TEXT    REFERENCES InputInv (id) ON DELETE CASCADE,
    id         TEXT    PRIMARY KEY,
    dgia       REAL,
    dvtinh     TEXT,
    ltsuat     TEXT,
    sluong     REAL,
    stbchu     TEXT,
    stckhau    REAL,
    stt        INTEGER,
    tchat      TEXT,
    ten        TEXT,
    thtcthue   TEXT,
    thtien     REAL,
    tlckhau    REAL,
    tsuat      REAL,
    tthue      REAL,
    sxep       TEXT,
    ttkhac     TEXT,
    dvtte      TEXT,
    tgia       REAL,
    tthhdtrung TEXT,
	PredictedHachToan    TEXT,
    HachToanProbability  REAL,
    PredictedMaHangHoa   TEXT,
    MaHangHoaProbability REAL,
    IsOutlierHachToan    INTEGER,
    IsOutlierMaHangHoa   INTEGER,
    PredictedAt          TEXT,
    PredictionMethod     TEXT,
    PredictionError      TEXT
);

CREATE INDEX IF NOT EXISTS IDX_InputInv_Lookup ON InputInv (khmshdon, khhdon, shdon);
CREATE INDEX IF NOT EXISTS IDX_InputInvDetails_idhdon ON InputInvDetails (idhdon);

-- Table: OutputInv
CREATE TABLE IF NOT EXISTS OutputInv (
    nbmst                    TEXT,
    khmshdon                 TEXT,
    khhdon                   TEXT,
    shdon                    TEXT,
    cqt                      TEXT,
    cttkhac                  TEXT,
    dvtte                    TEXT,
    hdon                     TEXT,
    hsgcma                   TEXT,
    hsgoc                    TEXT,
    hthdon                   TEXT,
    htttoan                  TEXT,
    id                       TEXT PRIMARY KEY
                                  NOT NULL,
    idtbao                   TEXT,
    khdon                    TEXT,
    khhdgoc                  TEXT,
    khmshdgoc                TEXT,
    lhdgoc                   TEXT,
    mhdon                    TEXT,
    mtdiep                   TEXT,
    mtdtchieu                TEXT,
    nbdchi                   TEXT,
    chma                     TEXT,
    chten                    TEXT,
    nbhdktngay               TEXT,
    nbhdktso                 TEXT,
    nbhdso                   TEXT,
    nblddnbo                 TEXT,
    nbptvchuyen              TEXT,
    nbstkhoan                TEXT,
    nbten                    TEXT,
    nbtnhang                 TEXT,
    nbtnvchuyen              TEXT,
    nbttkhac                 TEXT,
    ncma                     TEXT,
    ncnhat                   TEXT,
    ngcnhat                  TEXT,
    nky                      TEXT,
    nmdchi                   TEXT,
    nmmst                    TEXT,
    nmstkhoan                TEXT,
    nmten                    TEXT,
    nmtnhang                 TEXT,
    nmtnmua                  TEXT,
    nmttkhac                 TEXT,
    ntao                     TEXT,
    ntnhan                   TEXT,
    pban                     TEXT,
    ptgui                    TEXT,
    shdgoc                   TEXT,
    tchat                    TEXT,
    tdlap                    TEXT,
    tgia                     REAL,
    tgtcthue                 REAL,
    tgtthue                  REAL,
    tgtttbchu                TEXT,
    tgtttbso                 REAL,
    thdon                    TEXT,
    thlap                    TEXT,
    thttlphi                 TEXT,
    thttltsuat               TEXT,
    tlhdon                   TEXT,
    ttcktmai                 TEXT,
    tthai                    TEXT,
    ttkhac                   TEXT,
    tttbao                   TEXT,
    ttttkhac                 TEXT,
    ttxly                    TEXT,
    tvandnkntt               TEXT,
    mhso                     TEXT,
    ladhddt                  TEXT,
    mkhang                   TEXT,
    nbsdthoai                TEXT,
    nbdctdtu                 TEXT,
    nbfax                    TEXT,
    nbwebsite                TEXT,
    nbcks                    TEXT,
    nmsdthoai                TEXT,
    nmdctdtu                 TEXT,
    nmcmnd                   TEXT,
    nmcks                    TEXT,
    bhphap                   TEXT,
    hddunlap                 TEXT,
    gchdgoc                  TEXT,
    tbhgtngay                TEXT,
    bhpldo                   TEXT,
    bhpcbo                   TEXT,
    bhpngay                  TEXT,
    tdlhdgoc                 TEXT,
    tgtphi                   TEXT,
    unhiem                   TEXT,
    mstdvnunlhdon            TEXT,
    tdvnunlhdon              TEXT,
    nbmdvqhnsach             TEXT,
    nbsqdinh                 TEXT,
    nbncqdinh                TEXT,
    nbcqcqdinh               TEXT,
    nbhtban                  TEXT,
    nmmdvqhnsach             TEXT,
    nmddvchden               TEXT,
    nmtgvchdtu               TEXT,
    nmtgvchdden              TEXT,
    nbtnban                  TEXT,
    dcdvnunlhdon             TEXT,
    dksbke                   TEXT,
    dknlbke                  TEXT,
    thtttoan                 TEXT,
    msttcgp                  TEXT,
    cqtcks                   TEXT,
    gchu                     TEXT,
    kqcht                    TEXT,
    hdntgia                  TEXT,
    tgtkcthue                TEXT,
    tgtkhac                  TEXT,
    nmshchieu                TEXT,
    nmnchchieu               TEXT,
    nmnhhhchieu              TEXT,
    nmqtich                  TEXT,
    ktkhthue                 TEXT,
    qrcode                   TEXT,
    ttmstten                 TEXT,
    ladhddtten               TEXT,
    hdxkhau                  TEXT,
    hdxkptquan               TEXT,
    hdgktkhthue              TEXT,
    hdonLquans               TEXT,
    tthdclquan               TEXT,
    pdndungs                 TEXT,
    hdtbssrses               TEXT,
    hdTrung                  TEXT,
    isHDTrung                TEXT,
    LastDownloadedDetailDate TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
);


-- Table: OutputInvDetails
CREATE TABLE IF NOT EXISTS OutputInvDetails (
    idhdon     TEXT    REFERENCES OutputInv (id) ON DELETE CASCADE,
    id         TEXT    PRIMARY KEY,
    dgia       REAL,
    dvtinh     TEXT,
    ltsuat     TEXT,
    sluong     REAL,
    stbchu     TEXT,
    stckhau    REAL,
    stt        INTEGER,
    tchat      TEXT,
    ten        TEXT,
    thtcthue   TEXT,
    thtien     REAL,
    tlckhau    REAL,
    tsuat      REAL,
    tthue      REAL,
    sxep       TEXT,
    ttkhac     TEXT,
    dvtte      TEXT,
    tgia       REAL,
    tthhdtrung TEXT,
	PredictedHachToan    TEXT,
    HachToanProbability  REAL,
    PredictedMaHangHoa   TEXT,
    MaHangHoaProbability REAL,
    IsOutlierHachToan    INTEGER,
    IsOutlierMaHangHoa   INTEGER,
    PredictedAt          TEXT,
    PredictionMethod     TEXT,
    PredictionError      TEXT
);

CREATE INDEX IF NOT EXISTS IDX_OutputInv_Lookup ON OutputInv (khmshdon, khhdon, shdon);
CREATE INDEX IF NOT EXISTS IDX_OutputInvDetails_idhdon ON OutputInvDetails (idhdon);

